# Generated by Django 5.0.6 on 2024-08-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrototypeRequestDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000)),
                ('req', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
    ]
