# Generated by Django 5.0.6 on 2024-08-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_prototyperequestdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototyperequestdb',
            name='reqID',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
