# Generated by Django 5.0.6 on 2024-08-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_prototyperequestdb_reqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototyperequestdb',
            name='reqID',
            field=models.IntegerField(max_length=1000),
        ),
    ]
